import React, { createContext, useState, useContext } from 'react';

// Traductions pour l'interface
const translations = {
  fr: {
    // App.jsx
    appTitle: "Slide2LaTeX Converter",
    appDescription: "Transformez facilement vos présentations en documents LaTeX structurés avec notre outil d'IA - Générez des polycopiés de qualité en quelques clics !",
    
    // UploadForm.jsx
    formTitle: "Générateur de polycopié LaTeX",
    chooseFile: "Choisir un fichier PDF à convertir",
    fileInputLabel: "Fichier PDF",
    fileInputSecondary: "ou glisser-déposer votre fichier ici",
    noFileChosen: "Aucun fichier choisi",
    courseTitle: "Titre du document",
    generateLatex: "Générer le document",
    generateLatexDescription: "Convertir votre document en LaTeX professionnel",
    processingInProgress: "Traitement en cours...",
    pleaseWait: "Veuillez patienter...",
    selectedFile: "Fichier sélectionné :",
    
    // Section tarifs
    pricingTitle: "Nos Tarifs",
    pricingSubtitle: "Choisissez le forfait qui correspond le mieux à vos besoins",
    monthly: "Mensuel",
    yearly: "Annuel",
    billedAnnually: "Facturé annuellement",
    freePlan: "Gratuit",
    studentPlan: "Standard",
    proPlan: "Premium",
    teamPlan: "Pro",
    freePlanObjective: "Idéal pour tester la puissance de MyTekX sans engagement",
    studentPlanObjective: "Pensé pour ceux qui utilisent MyTekX régulièrement",
    proPlanObjective: "Pour ceux qui veulent des résultats ultra-pro et des documents prêts à imprimer",
    teamPlanObjective: "Pour les structures avec de gros volumes ou besoins spécifiques",
    freeFeature1: "5 documents maximum à vie",
    freeFeature2: "20 pages par document",
    freeFeature3: "Modèle IA basique",
    premiumFeature1: "15 documents par mois",
    premiumFeature2: "50 pages par document",
    proFeature1: "30 documents par mois",
    proFeature2: "70 pages par document",
    teamFeature1: "Documents et pages illimités",
    teamFeature2: "Traitement MyTekX illimité + humain",
    teamFeature3: "Support prioritaire 24/7",
    startFree: "Commencer gratuitement",
    getPremium: "Choisir Standard",
    goProNow: "Passer Premium",
    contactUs: "Nous contacter",
    mostPopular: "Le plus populaire",
    unlimited: "illimité",
    everything: "tout",
    inProPlan: "du plan Premium",
    customQuote: "Sur devis",
    month: "mois",
    priority: "prioritaire",
    support: "support",
    satisfactionGuarantee: "Garantie satisfaction",
    moneyBackGuarantee: "Essayez MyTekX sans risque - Garantie satisfait ou remboursé pendant 14 jours",
    commonQuestions: "Questions fréquentes",
    pricingQuestion1: "Puis-je changer de plan à tout moment ?",
    pricingAnswer1: "Oui, vous pouvez changer de plan à tout moment. La différence sera calculée au prorata.",
    pricingQuestion2: "Comment fonctionne la garantie satisfait ou remboursé ?",
    pricingAnswer2: "Si vous n'êtes pas satisfait dans les 14 premiers jours, nous vous remboursons intégralement, sans question.",
    pricingQuestion3: "Y a-t-il des frais cachés ?",
    pricingAnswer3: "Non, nos prix sont transparents et incluent toutes les fonctionnalités mentionnées. Pas de surprise.",
    
    // Sélection de plage de pages
    pageRangeToggle: "Sélectionner des pages spécifiques",
    pageRangeFrom: "De",
    pageRangeTo: "À",
    pageRangeInfo: "Sélection actuelle :",
    pageRangeCount: "pages sélectionnées",
    pageRangeAll: "Toutes les pages",
    pageRangeError: "La page de début doit être inférieure à la page de fin",
    pageRangeOutOfBounds: "Veuillez entrer un numéro de page valide (1 à {max})",
    selectPageRange: "Sélectionner des pages spécifiques",
    fromPage: "De",
    toPage: "À",
    selectedPagesInfo: "Vous allez traiter",
    pagesOut: "pages sur",
    pageOut: "page sur",
    allPages: "Toutes les pages",
    firstHalf: "Première moitié",
    secondHalf: "Deuxième moitié",
    first10: "Premières 10 pages",
    
    // Choix du type de document
    docTypeQuestion: "Type de document à convertir ?",
    docTypeSlidesTitle: "Diapositives",
    docTypeDocumentTitle: "Document Texte",
    slidesDescription: "Présentations, diapositives et cours magistraux",
    documentDescription: "Articles, rapports et documents textuels",
    
    // Statuts de chargement
    wakingUpServer: "Réveil du serveur...",
    serverReady: "Serveur prêt !",
    preparingSend: "Préparation de l'envoi...",
    sendingFile: "Envoi du fichier au serveur...",
    processingFile: "Traitement du fichier par le serveur...",
    generatingLatex: "Génération du fichier LaTeX...",
    success: "Terminé avec succès !",
    errorProcessing: "Erreur lors du traitement",
    requestCancelled: "Requête annulée",
    documentSaved: "Document enregistré avec succès !",
    
    // Mots clés pour les emojis de statut
    waking: "Réveil",
    sending: "Envoi",
    processing: "Traitement",
    generating: "Génération",
    completed: "Terminé",
    error: "Erreur",
    
    // Conseils pendant le chargement (tips)
    tip1: "LaTeX a été créé en 1984 par Leslie Lamport.",
    tip2: "LaTeX est utilisé par plus de 80% des mathématiciens.",
    tip3: "Le nom 'LaTeX' vient de 'Lamport TeX'.",
    tip4: "LaTeX est particulièrement apprécié pour sa gestion des formules mathématiques.",
    tip5: "LaTeX est un logiciel libre et gratuit.",
    tip6: "LaTeX est utilisé par les plus grandes universités du monde.",
    tip7: "LaTeX permet de générer des bibliographies automatiquement avec BibTeX.",
    tip8: "La plupart des publications scientifiques sont rédigées en LaTeX.",
    tip9: "Il existe plus de 5000 packages pour LaTeX, chacun offrant des fonctionnalités supplémentaires.",
    tip10: "LaTeX peut générer des documents dans n'importe quelle langue.",
    tip11: "LaTeX permet de créer des présentations, des posters, des CV, et même des livres entiers.",
    tip12: "TeX, le système sur lequel LaTeX est basé, a été créé par Donald Knuth en 1978.",
    tip13: "LaTeX est prononcé 'La-tek' et non 'La-teks'.",
    
    // Annulation de requête
    cancelRequest: "Annuler la requête",
    requestCancelledByUser: "Requête annulée par l'utilisateur",
    
    // Messages d'erreur
    errorNoFile: "Veuillez sélectionner un fichier PDF",
    errorServerNotReady: "Impossible de réveiller le serveur. Veuillez réessayer dans quelques instants.",
    errorNoFileToDownload: "Aucun fichier à télécharger",
    errorNoLogsToDownload: "Aucun fichier de logs d'erreur à télécharger",
    
    // Onglet Général
    pdfFile: "Fichier PDF",
    pageDetected: "page détectée",
    pagesDetected: "pages détectées",
    
    // Onglets
    tabGeneral: "Général",
    tabGeneralDesc: "Fichier et titre",
    tabLanguage: "Langues",
    tabLanguageDesc: "Source et cible",
    tabLayout: "Mise en page",
    tabLayoutDesc: "Format et marges",
    tabContent: "Contenu",
    tabContentDesc: "Sections spéciales",
    tabAI: "IA",
    tabAIDesc: "Modèle et qualité",
    
    // Langues
    sourceLanguage: "Langue source",
    targetLanguage: "Langue cible",
    searchLanguage: "Rechercher une langue...",
    translationNote: "La traduction conservera la mise en page et les formules mathématiques.",
    
    // Mise en page
    pageFormat: "Format de page",
    fontSize: "Taille de police (pt)",
    paragraphSpacing: "Espacement des paragraphes",
    spacingSingle: "Simple (1.0)",
    spacingComfortable: "Confortable (1.15)",
    spacingWide: "Large (1.5)",
    spacingDouble: "Double (2.0)",
    margins: "Marges (cm)",
    marginTop: "Haut",
    marginRight: "Droite",
    marginBottom: "Bas",
    marginLeft: "Gauche",
    fontFamily: "Police du document",
    fontDefault: "Computer Modern (défaut)",
    fontTimes: "Times New Roman",
    fontHelvetica: "Helvetica",
    fontPalatino: "Palatino",
    fontBookman: "Bookman",
    fontCharter: "Charter",
    fontLibertine: "Libertine",
    resetMargins: "Réinitialiser les marges",
    documentMargins: "Marges du document",
    
    // Contenu
    includeIntuition: "Inclure les intuitions",
    includeRetenir: "Inclure les points à retenir",
    includeVulgarisation: "Inclure la vulgarisation",
    includeRecap: "Inclure les fiches récapitulatives",
    includeGraph: "Inclure les graphes",
    includeShapes: "Inclure les formes géométriques",
    shapesDescription: "Inclure les formes géométriques dans le document en utilisant LaTeX/TikZ",
    graphDescription: "Inclure les graphes dans le document",
    includeFinalRecapPage: "Inclure la synthèse finale",
    configure: "Configurer",
    vulgarizationNone: "Aucune vulgarisation",
    vulgarizationMinimal: "Niveau 1 - Minimal",
    vulgarizationLight: "Niveau 2 - Léger",
    vulgarizationMedium: "Niveau 3 - Moyen",
    vulgarizationHigh: "Niveau 4 - Analogies quotidiennes",
    vulgarizationMaximal: "Niveau 5 - Métaphores créatives",
    includeIllustrations: "Inclure les descriptions des illustrations",
    includeDefinitions: "Inclure les définitions",
    extractRealImages: "Extraire et inclure des images réelles",
    highlightMode: "Mode surligneur IA : surligner les éléments importants à retenir",
    detectGraphs: "Détecter les graphes",
    pedagogicalElements: "Éléments pédagogiques",
    intuitionDescription: "Intuition: fournir une explication intuitive du concept abordé dans cette section. Elle aide à comprendre l'idée de manière plus concrète.",
    retenirDescription: "Points clés: résumer les points essentiels à retenir de cette section. Il inclut les formules et définitions clés.",
    vulgarisationDescription: "Explication simplifiée: expliquer les concepts de manière simplifiée. Elle utilise des analogies et un vocabulaire accessible pour faciliter la compréhension.",
    summariesAndOverviews: "Résumés et aperçus",
    recapDescription: "Résumé: résumer le concept principal de cette section.",
    finalRecapDescription: "Synthèse finale: résumer les points essentiels de l'ensemble du document.",
    visualElements: "Éléments visuels",
    illustrationsDescription: "Illustrations: inclure les descriptions des illustrations dans le document.",
    extractImagesDescription: "Extraire et inclure des images",
    otherFeatures: "Autres fonctionnalités",
    definitionsDescription: "Définitions: inclure les définitions clés de cette section.",
    definitionsTitle: "Définitions",
    definitionsPreviewText: "Cette boîte contient les définitions clés de cette section. Elle fournit une explication précise et formelle des concepts abordés.",
    highlightDescription: "Surligner les éléments importants à retenir",
    vulgarizationLevel: "Niveau de vulgarisation",

    // IA
    processingQuality: "Qualité du traitement :",
    fast: "Rapide - Qualité basique",
    standard: "Standard - Équilibré",
    highQuality: "Haute qualité - Meilleur contenu",
    premium: "Premium - Qualité maximale",
    estimatedTime: "Temps estimés pour un document de",
    estimatedTimeLabel: "Temps estimé :",
    pages: "pages",
    loadDocToSeeTime: "Chargez un document pour voir les temps estimés précis",
    modelFastTitle: "Rapide",
    modelFastDesc: "Moteur d'IA avec analyse rapide - Pour tests ou documents simples",
    modelStandardTitle: "Standard",
    modelStandardDesc: "Moteur d'IA avec analyse standard - Pour l'usage courant",
    modelHighQualityTitle: "Haute qualité",
    modelHighQualityDesc: "Moteur d'IA avec analyse approfondie - Pour du contenu technique complexe",
    modelPremiumTitle: "Premium",
    modelPremiumDesc: "Moteur d'IA ultra avancé - Qualité supérieure et traitement plus rapide pour tous types de documents",
    analyzingSlides: "Analyse des diapositives...",
    extractingContent: "Extraction du contenu...",
    generatingLatex: "Génération du code LaTeX...",
    formattingDocument: "Mise en forme du document...",
    finalizingOutput: "Finalisation de la sortie...",
    preparingDownload: "Préparation du téléchargement...",
    
    // Instructions spécifiques de l'IA
    aiInstructionsTitle: "Instructions spécifiques",
    aiInstructionsInfo: "Dites-moi comment vous souhaitez personnaliser votre document LaTeX :",
    aiInstructionsExample1: "« Mettez l'accent sur les exemples pratiques »",
    aiInstructionsExample2: "« Utilisez un style plus formel pour l'explication des concepts »",
    aiInstructionsExample3: "« Simplifiez davantage les concepts mathématiques avancés »",
    aiInstructionsPlaceholder: "Tapez vos instructions spécifiques ici...",
    
    // Téléchargement
    downloadFilename: "Nom du fichier à télécharger :",
    downloadLatex: "Télécharger le fichier LaTeX",
    downloadPDF: "Télécharger le PDF",
    downloadLogs: "Télécharger les logs d'erreur",
    downloadNote: "Note: Le fichier LaTeX est prêt à être compilé sur Overleaf. Le PDF peut ne pas être disponible si la compilation sur le serveur a échoué.",
    
    // Interface langue
    switchToEnglish: "English",
    switchToFrench: "Français",

    backToHome: "Retour à l'accueil",
    // Erreurs
    errorRefresh: "Essayez de rafraîchir la page ou de réessayer dans quelques instants.",
    
    // Chargement
    loadingHint: "Le traitement est généralement lent... C'est l'occasion parfaite pour aller boire un café ! ☕",
    
    // Modals de configuration
    configIntuition: "Configuration des boîtes \"Intuition\"",
    configRetenir: "Configuration des boîtes \"À retenir\"",
    configVulgarisation: "Configuration des boîtes \"Vulgarisation\"",
    configRecap: "Configuration des boîtes \"Récapitulatif\"",
    configDefinitions: "Configuration des boîtes \"Définitions\"",
    preview: "Aperçu",
    color: "Couleur:",
    titleFont: "Police du titre:",
    contentFont: "Police du contenu:",
    icon: "Icône:",
    borderStyle: "Style de bordure:",
    background: "Arrière-plan:",
    close: "Fermer",
    save: "Enregistrer",
    upgradeForMoreFeatures: "Upgrade pour plus de fonctionnalités",
    upgradeToPremium: "Passer à la version Premium",
    
    // PDF Preview
    pdfPreview: "Aperçu du PDF",
    showPdfPreview: "Afficher l'aperçu PDF",
    saveToDocuments: "Enregistrer dans Mes Documents",
    editDocument: "Modifier le document",
    
    // Titres des boîtes
    intuitionTitle: "Intuition",
    retenirTitle: "À retenir",
    vulgarisationTitle: "Vulgarisation simple",
    definitionsTitle: "Définitions",
    recapTitle: "Fiche Récapitulative",
    
    // Textes d'aperçu
    intuitionPreviewText: "Cette boîte fournit une explication intuitive du concept abordé dans cette section. Elle aide à comprendre l'idée de manière plus concrète.",
    retenirPreviewText: "Cette boîte contient les points essentiels à retenir de cette section. Elle résume les formules et définitions clés.",
    vulgarisationPreviewText: "Cette boîte explique les concepts de façon simplifiée. Elle utilise des analogies et un vocabulaire accessible pour faciliter la compréhension.",
    definitionsPreviewText: "Cette boîte contient les définitions clés de cette section. Elle fournit une explication précise et formelle des concepts abordés.",
    // Textes de récapitulatif
    recapObjective: "Objectif :",
    recapObjectiveText: "Résumer le concept principal de cette section.",
    recapPrinciple: "Principe central :",
    recapPrincipleText: "Explication concise de l'idée fondamentale.",
    recapPoints: "Points essentiels :",
    recapPoint1: "Premier point important",
    recapPoint2: "Second point important",
    recapPoint3: "Troisième point important",
    
    // Couleurs
    colorGreen: "Vert",
    colorBlue: "Bleu",
    colorRed: "Rouge",
    colorYellow: "Jaune",
    colorPurple: "Violet",
    colorGray: "Gris",
    colorOrange: "Orange",
    colorTeal: "Turquoise",
    
    // Icônes
    iconBulb: "Ampoule",
    iconThought: "Bulle de pensée",
    iconBrain: "Cerveau",
    iconCompass: "Boussole",
    iconMagic: "Baguette magique",
    iconBookmark: "Marque-page",
    iconCheck: "Checkmark",
    iconStar: "Étoile",
    iconExclamation: "Point d'exclamation",
    iconMemory: "Mémoire",
    iconComment: "Commentaire",
    iconInfo: "Information",
    iconQuestion: "Question",
    iconGlasses: "Lunettes",
    iconHand: "Main qui pointe",
    iconList: "Liste",
    iconAltList: "Liste alternative",
    iconTasks: "Tâches",
    iconDocument: "Document",
    iconChart: "Graphique",
    profile: "Profil",
    betaCodeSuccess: "Code bêta accepté",
    betaTitle: "Version bêta",
    betaDescription: "Cette version est en cours de développement et n'est pas encore disponible pour le public. Merci de patienter et de nous contacter si vous avez des questions ou des suggestions.",
    giveFeedback: "Donne-nous ton avis en 1 min !",
    betaCode: "Code bêta",
    betaCodeInput: "Entrez votre code bêta",
    betaCodeButton: "Valider le code bêta",
    betaCodeError: "Code bêta invalide",
    betaBadge: "Bêta privée",
    getStarted: "Commencer maintenant !",



    
    // Styles de bordure
    borderSimple: "Simple (1pt)",
    borderDouble: "Double",
    borderDotted: "Pointillés",
    borderDashed: "Tirets",
    borderThick: "Épais (3pt)",
    
    // Arrière-plans
    bgSolid: "Uni (défaut)",
    bgGrid: "Grille",
    bgDots: "Points",
    bgCrosshatch: "Hachures",
    bgGradient: "Dégradé",

    // Chat Interface
    openChat: "Ouvrir l'assistant IA",
    closeChat: "Fermer l'assistant",
    deleteMessage: "Supprimer ce message",
    sendMessage: "Envoyer",
    chatPlaceholder: "Tapez vos instructions ici...",
    chatTitle: "Assistant IA",
    chatDescription: "Je vous aide à personnaliser votre document",

    // Page Profil
    myProfile: "Mon Profil",
    backToApp: "Retour à l'application",
    loadingProfile: "Chargement de votre profil...",
    profileOverview: "Aperçu du profil",
    dashboard: "Tableau de bord",
    myDocuments: "Mes documents",
    preferences: "Préférences",
    accountSettings: "Paramètres du Compte",
    affiliateProgram: "Programme d'Affiliation",
    comingSoon: "Bientôt disponible",
    underDevelopment: "En cours de développement",
    underDevelopmentMessage: "Cette fonctionnalité est actuellement en cours de développement. Elle sera bientôt disponible !",
    stayTuned: "Restez connecté pour les mises à jour.",
    viewProfile: "Voir le profil",
    myProfile: "Mon Profil",
    uploadPhoto: "Télécharger une photo",
    registrationDate: "Date d'inscription",
    accountStatus: "Statut du compte",
    statusActive: "Actif",
    statusInactive: "Inactif",
    statusPending: "En attente",
    betaTester: "Testeur Bêta",
    memberSince: "Membre depuis",
    invalidDate: "Date invalide",
    defaultUsername: "Utilisateur",
    changePhoto: "Changer la photo",
    profilePhotoAlt: "Photo de profil",
    photoUploadDev: "La fonctionnalité de téléchargement de photo sera disponible prochainement.",
    connected: "Connecté",
    logout: "Déconnexion",
    documents: "Documents",
    searchDocuments: "Rechercher des documents...",
    allDocuments: "Tous les documents",
    slidesOnly: "Diapositives uniquement",
    textDocumentsOnly: "Documents texte uniquement",
    noDocumentsFound: "Aucun document trouvé pour cette recherche",
    loadingDocuments: "Chargement de vos documents...",
    betaCode: "Code Bêta ",
    modelHigh_qualityTitle: "Haute qualité",
    modelHigh_qualityDesc: "Moteur d'IA avec analyse approfondie - Pour du contenu technique complexe",
    

    // Mois pour le formatage de date
    january: "janvier",
    february: "février",
    march: "mars",
    april: "avril",
    may: "mai",
    june: "juin",
    july: "juillet",
    august: "août",
    september: "septembre",
    october: "octobre",
    november: "novembre",
    december: "décembre",

    // Formulaire d'inscription
    completeYourProfile: "Complétez votre profil",
    registrationDescription: "Veuillez compléter les informations suivantes pour personnaliser votre expérience. Cela nous aidera à mieux comprendre vos besoins et à améliorer notre service.",
    displayName: "Nom d'affichage",
    displayNamePlaceholder: "Comment souhaitez-vous être appelé ?",
    occupation: "Profession",
    selectOccupation: "Sélectionnez votre profession",
    occupationStudent: "Étudiant",
    occupationTeacher: "Enseignant",
    occupationResearcher: "Chercheur",
    occupationProfessional: "Professionnel",
    occupationOther: "Autre",
    organization: "Organisation",
    organizationPlaceholder: "Nom de votre université, école ou entreprise",
    fieldOfStudy: "Domaine d'étude",
    fieldOfStudyPlaceholder: "Ex: Mathématiques, Informatique, Physique",
    country: "Pays",
    selectCountry: "Sélectionnez votre pays",
    countryFrance: "France",
    countryUSA: "États-Unis",
    countryCanada: "Canada",
    countrySwitzerland: "Suisse",
    countryBelgium: "Belgique",
    countryOther: "Autre pays",
    bio: "Bio (facultatif)",
    bioPlaceholder: "Parlez-nous un peu de vous et de ce que vous espérez accomplir avec MyTekX",
    skip: "Ignorer pour l'instant",
    saveProfile: "Enregistrer le profil",
    saving: "Enregistrement...",
    privacyNote: "En enregistrant votre profil, vous acceptez notre politique de confidentialité. Vos informations ne seront jamais partagées sans votre consentement.",
    errorRequiredField: "Ce champ est requis",
    errorNameTooShort: "Le nom doit contenir au moins 3 caractères",
    errorSavingData: "Une erreur est survenue lors de l'enregistrement. Veuillez réessayer.",
    settings: "Paramètres",
    noDocumentsYet: "Vous n'avez pas encore de documents",
    viewDocumentsDesc: "Cliquez pour voir et gérer vos documents",
    backToProfile: "Retour au profil",

    // Documents
    searchDocuments: "Rechercher des documents...",
    allDocuments: "Tous les documents",
    slidesOnly: "Diapositives uniquement",
    textDocumentsOnly: "Documents texte uniquement",
    noDocumentsFound: "Aucun document trouvé pour cette recherche",
    loadingDocuments: "Chargement de vos documents...",
    viewDocument: "Voir le document",
    downloadDocument: "Télécharger le document",
    viewPDF: "Voir le PDF",
    downloadTex: "Affiche une fenêtre avec le code LaTeX - Copier-coller ce texte dans un éditeur LaTeX (comme Overleaf) pour le modifier",
    deleteDocument: "Supprimer le document",
    delete: "Supprimer",
    confirmDeleteTitle: "Confirmation de suppression",
    confirmDelete: "Êtes-vous sûr de vouloir supprimer ce document ? Cette action est irréversible.",
    confirmDeleteButton: "Oui, supprimer",
    cancel: "Annuler",
    documentDeleted: "Document supprimé avec succès",
    deleteError: "Erreur lors de la suppression du document",
    page: "page",
    pages: "pages",
    slides: "Diapositives",
    textDocument: "Document texte",
    downloadSection: "Séction de téléchargement",
    filenameLabel: "Nom du fichier",
    finalCtaTitle: "Prêt à transformer votre façon d'étudier ?",
    finalCtaSubtitle: "COMMENCEZ DÈS AUJOURD'HUI",
    finalCtaDescription: "Rejoignez les étudiants et les enseignants qui utilisent déjà MyTekX pour améliorer leur expérience d'apprentissage.",
    finalCtaTryButton: "Essayer gratuitement",
    finalCtaLearnButton: "En savoir plus",
    
    // Guide Section
    guideTitle: "Guide d'utilisation",
    guideSubtitle: "Apprenez à utiliser MyTekX efficacement",
    
    // Guide Categories
    guideGettingStartedTitle: "Premiers pas",
    guideGettingStartedDesc: "Commencer avec MyTekX",
    guideConversionTitle: "Conversion",
    guideConversionDesc: "Convertir vos documents",
    guideTipsTitle: "Conseils",
    guideTipsDesc: "Optimiser vos résultats",
    guideFaqTitle: "FAQ",
    guideFaqDesc: "Questions fréquentes",
    downloadLatexFile: "Télécharger le fichier LaTeX",
    guideWelcomeTitle: "Bienvenue sur MyTekX",
    guideWelcomeContent: "MyTekX est un outil puissant qui vous permet de convertir facilement vos présentations PowerPoint et documents en LaTeX de haute qualité.",
    guideWelcomeStep1: "Créez votre compte gratuitement",
    guideWelcomeStep2: "Téléchargez votre document",
    guideWelcomeStep3: "Choisissez vos options de conversion",
    guideWelcomeStep4: "Téléchargez votre fichier LaTeX",
    guideSupportedFilesTitle: "Types de fichiers supportés",
    guideSupportedFilesContent: "MyTekX prend en charge plusieurs formats de fichiers :",
    guideSupportedFilesStep1: "PowerPoint (.pptx, .ppt)",
    guideSupportedFilesStep2: "Documents Word (.docx, .doc)",
    guideSupportedFilesStep3: "PDF (conversion limitée)",
    guideSupportedFilesStep4: "Images (.jpg, .png, .gif)",
    guideConversionProcessTitle: "Processus de conversion",
    guideConversionProcessContent: "Suivez ces étapes pour une conversion optimale :",
    guideConversionProcessStep1: "Préparez votre document source",
    guideConversionProcessStep2: "Vérifiez la qualité des images",
    guideConversionProcessStep3: "Simplifiez les animations complexes",
    guideConversionProcessStep4: "Utilisez des polices standard",
    guideConversionProcessStep5: "Organisez votre contenu de manière claire",
    
    guideOutputOptionsTitle: "Options de sortie",
    guideOutputOptionsContent: "Choisissez le format qui vous convient :",
    guideOutputOptionsStep1: "PDF - Pour visualisation immédiate",
    guideOutputOptionsStep2: "TEX - Code LaTeX source",
    guideOutputOptionsStep3: "Word - Format éditable (.docx)",
    guideOptimizationTitle: "Optimisation des résultats",
    guideOptimizationContent: "Conseils pour améliorer la qualité de conversion :",
    guideOptimizationStep1: "Utilisez des images haute résolution",
    guideOptimizationStep2: "Évitez les polices exotiques",
    guideOptimizationStep3: "Structurez vos titres hiérarchiquement",
    guideOptimizationStep4: "Limitez les effets visuels complexes",
    guideOptimizationStep5: "Testez sur un petit document d'abord",
    
    guideTablesTitle: "Gestion des tableaux",
    guideTablesContent: "Pour de meilleurs résultats avec les tableaux :",
    guideTablesStep1: "Utilisez des tableaux simples",
    guideTablesStep2: "Évitez les cellules fusionnées",
    guideTablesStep3: "Gardez un nombre raisonnable de colonnes",
    guideTablesStep4: "Utilisez des bordures claires",
    
    // FAQ Section
    guideFaqQuestionsTitle: "Questions fréquentes",
    guideFaqQuestionsContent: "Réponses aux questions les plus courantes :",
    guideFaqQuestion1: "Q: Combien de temps prend la conversion ? R: Entre 30 secondes et 2 minutes",
    guideFaqQuestion2: "Q: Y a-t-il une limite de taille ? R: 50MB maximum par fichier",
    guideFaqQuestion3: "Q: Puis-je modifier le code LaTeX ? R: Oui, vous recevez le code source",
    guideFaqQuestion4: "Q: Les images sont-elles conservées ? R: Oui, avec optimisation automatique",
    guideFaqQuestion5: "Q: Que faire si la conversion échoue ? R: Contactez le support avec votre fichier",

    // FAQ section
    faqTitle: "Questions fréquentes",
    faqSubtitle: "Vous avez des questions ? Nous avons les réponses.",

    // Footer section
    footerNavigation: "Navigation",
    footerHome: "Accueil",
    footerResources: "Ressources",
    footerBlog: "Blog",
    footerTutorials: "Tutoriels",
    footerSupport: "Support",
    footerDocumentation: "Documentation",
    footerContact: "Contact",
    footerContactUs: "Nous contacter",
    footerRights: "Tous droits réservés",
    comingSoon: "Bientôt disponible",
    privacyPolicy: "Politique de confidentialité",
    termsOfService: "Conditions d'utilisation",
    legalNotice: "Mentions légales",
    requestCancelledRefresh: "Requête annulée. Actualisez la page pour réessayer.",
    // Final CTA section
    finalCtaTitle: "Prêt à transformer votre façon d'étudier ?",
    finalCtaSubtitle: "COMMENCEZ DÈS AUJOURD'HUI",
    finalCtaDescription: "Rejoignez les étudiants et les enseignants qui utilisent déjà MyTekX pour améliorer leur expérience d'apprentissage.",
    finalCtaTryButton: "Essayer gratuitement",
    finalCtaLearnButton: "En savoir plus",
    personalInfo: "Informations personnelles",
    privacySecurity: "Confidentialité et Sécurité",
    latinAlphabetOnly: "Alphabets latins uniquement",
    latinAlphabetMessage: "Actuellement, seules les langues cibles utilisant l'alphabet latin sont disponibles. Les langues avec d'autres alphabets (arabe, chinois, hébreu, cyrillique, etc.) sont en cours de développement.",
    otherAlphabetsComingSoon: "Autres alphabets bientôt disponibles",
    lastUpdated: "Dernière mise à jour",
    // Confidentiality section
    whoWeAre: "Qui sommes-nous ?",
    privacyPolicyIntro: "Bienvenue sur MyTekX, un outil puissant qui vous permet de convertir facilement vos présentations PowerPoint et documents en LaTeX de haute qualité.",
    dataCollected: "Données collectées",
    dataCollectedIntro: "Lorsque vous utilisez MyTekX, nous collectons certaines informations pour fournir et améliorer notre service. Cette information est utilisée pour personnaliser votre expérience et analyser comment vous utilisez le service.",
    dataItem1: "Votre adresse e-mail",
    dataItem2: "Vos données d'utilisation",
    dataItem3: "Vos documents",
    dataItem4: "Vos informations de profil",
    dataItem5: "Vos interactions avec le service",
    dataItem6: "Vos informations de matériel",
    dataItem7: "Votre adresse IP",
    howWeUseData: "Comment nous utilisons vos données",
    dataUsageDescription: "Nous utilisons vos données pour personnaliser votre expérience, analyser votre utilisation et améliorer notre service. Nous ne partageons pas vos données avec des tiers sans votre consentement.",
    dataSharing: "Partage de données",
    dataSharingPolicy: "Nous ne partageons pas vos données avec des tiers sans votre consentement.",
    dataSecurity: "Sécurité des données",
    dataSecurityDescription: "Nous mettons en œuvre des mesures de sécurité pour protéger vos données. Cependant, aucune méthode de transmission sur internet n'est 100% sûre.",
    userRights: "Droits des utilisateurs",
    userRightsDescription: "Vous avez le droit d'accéder, de corriger ou de supprimer vos données. Vous pouvez également demander que nous cessions d'utiliser vos données pour certaines finalités.",
    contactForRights: "Contactez-nous pour plus d'informations sur vos droits.",
    cookies: "Cookies",
    cookiesDescription: "Nous utilisons des cookies pour personnaliser votre expérience. Vous pouvez désactiver les cookies dans vos paramètres de navigateur.",
    policyChanges: "Changements de politique",
    policyChangesDescription: "Nous conservons le droit de mettre à jour cette politique de confidentialité à tout moment. Nous vous informerons de changements significatifs via e-mail ou par le biais du service.",
    
    
  },
  en: {
    // App.jsx
    appTitle: "Slide2LaTeX Converter",
    appDescription: "Easily transform your presentations into structured LaTeX documents with our AI tool - Generate quality handouts in just a few clicks!",
    filenameLabel: "File name",
    downloadLatexFile: "Download LaTeX file",
    // UploadForm.jsx
    formTitle: "LaTeX Document Generator",
    chooseFile: "Choose PDF File to convert",
    fileInputLabel: "PDF File",
    noFileChosen: "No file chosen",
    fileInputSecondary: "or drag and drop your file here",
    courseTitle: "Document Title",
    generateLatex: "Generate document",
    generateLatexDescription: "Convert your document to professional LaTeX",
    processingInProgress: "Processing...",
    pleaseWait: "Please wait...",
    selectedFile: "Selected file:",
    betaCode: "Beta code",
    // Guide Categories
    guideGettingStartedTitle: "Getting started",
    guideGettingStartedDesc: "Start with MyTekX",
    guideConversionTitle: "Conversion",
    guideConversionDesc: "Convert your documents",
    guideTipsTitle: "Tips",
    guideTipsDesc: "Optimize your results",
    guideFaqTitle: "FAQ",
    guideFaqDesc: "Frequently asked questions", 
    guideWelcomeTitle: "Welcome to MyTekX",
    guideWelcomeContent: "MyTekX is a powerful tool that allows you to easily convert your PowerPoint presentations and documents into high-quality LaTeX documents.",
    guideWelcomeStep1: "Create your account for free",
    guideWelcomeStep2: "Upload your document",
    guideWelcomeStep3: "Choose your conversion options",
    guideWelcomeStep4: "Download your LaTeX file",
    guideSupportedFilesTitle: "Supported file types",
    guideSupportedFilesContent: "MyTekX supports several file formats:",
    guideSupportedFilesStep1: "PowerPoint (.pptx, .ppt)",
    guideSupportedFilesStep2: "Documents Word (.docx, .doc)",
    guideSupportedFilesStep3: "PDF (limited conversion)",
    guideSupportedFilesStep4: "Images (.jpg, .png, .gif)",
    guideConversionProcessTitle: "Conversion process",
    guideConversionProcessContent: "Follow these steps for optimal conversion:",
    guideConversionProcessStep1: "Prepare your source document",
    guideConversionProcessStep2: "Check the quality of the images",
    guideConversionProcessStep3: "Simplify complex animations",
    guideConversionProcessStep4: "Use standard fonts",
    guideOutputOptionsTitle: "Output options",
    guideOutputOptionsContent: "Choose the format that suits you:",
    guideOutputOptionsStep1: "PDF - For immediate viewing",
    guideOutputOptionsStep2: "TEX - LaTeX source code",
    guideOutputOptionsStep3: "Word - Editable (.docx) format",
    guideOptimizationTitle: "Optimization of results",
    guideTitle: "User guide",
    guideSubtitle: "Learn how to use MyTekX efficiently",
    guideGettingStartedTitle: "Getting started",
    guideGettingStartedDesc: "Start with MyTekX",
    guideConversionTitle: "Conversion",
    guideConversionDesc: "Convert your documents",
    guideTipsTitle: "Tips",
    guideTipsDesc: "Optimize your results",

    

    // Pricing section
    pricingTitle: "Our Pricing",
    pricingSubtitle: "Choose the plan that best fits your needs",
    monthly: "Monthly",
    yearly: "Yearly",
    billedAnnually: "Billed annually",
    freePlan: "Free",
    studentPlan: "Standard",
    proPlan: "Premium",
    teamPlan: "Pro",
    freePlanObjective: "Perfect to test MyTekX's power with no commitment",
    studentPlanObjective: "Designed for those who use MyTekX regularly",
    proPlanObjective: "For those who want ultra-pro results and print-ready documents",
    teamPlanObjective: "For organizations with high volume or specific needs",
    freeFeature1: "5 documents maximum lifetime",
    freeFeature2: "20 pages per document",
    freeFeature3: "Basic AI model",
    premiumFeature1: "15 documents per month",
    premiumFeature2: "50 pages per document",
    proFeature1: "30 documents per month",
    proFeature2: "70 pages per document",
    teamFeature1: "Unlimited documents and pages",
    teamFeature2: "MyTekX unlimited processing + human",
    teamFeature3: "24/7 priority support",
    startFree: "Start for free",
    getPremium: "Choose Standard",
    goProNow: "Go Premium",
    contactUs: "Contact us",
    mostPopular: "Most popular",
    unlimited: "unlimited",
    everything: "everything",
    inProPlan: "in Premium plan",
    customQuote: "Custom quote",
    month: "month",
    priority: "priority",
    support: "support",
    satisfactionGuarantee: "Satisfaction guarantee",
    moneyBackGuarantee: "Try MyTekX risk-free - 14-day money-back guarantee",
    commonQuestions: "Common questions",
    pricingQuestion1: "Can I change plans anytime?",
    pricingAnswer1: "Yes, you can change plans at any time. The difference will be prorated.",
    pricingQuestion2: "How does the money-back guarantee work?",
    pricingAnswer2: "If you're not satisfied within the first 14 days, we'll refund you in full, no questions asked.",
    pricingQuestion3: "Are there any hidden fees?",
    pricingAnswer3: "No, our prices are transparent and include all features mentioned. No surprises.",
    // Page Range Selection
    pageRangeToggle: "Select specific pages",
    pageRangeFrom: "From",
    pageRangeTo: "To",
    pageRangeInfo: "Current selection:",
    pageRangeCount: "pages selected",
    pageRangeAll: "All pages",
    pageRangeError: "Start page must be less than end page",
    pageRangeOutOfBounds: "Please enter a valid page number (1 to {max})",
    selectPageRange: "Select specific pages",
    fromPage: "From",
    toPage: "To",
    selectedPagesInfo: "You will process",
    pagesOut: "pages out of",
    pageOut: "page out of",
    allPages: "All pages",
    firstHalf: "First half",
    secondHalf: "Second half",
    first10: "First 10",
    
    // Document type selection
    docTypeQuestion: "What type of document would you like to convert?",
    docTypeSlidesTitle: "Slides",
    docTypeDocumentTitle: "Text document",
    slidesDescription: "Presentations, slides, and lecture notes",
    documentDescription: "Articles, reports, and text documents",
    
    // Statuts de chargement
    wakingUpServer: "Waking up server...",
    serverReady: "Server ready!",
    preparingSend: "Preparing to send...",
    sendingFile: "Sending file to server...",
    processingFile: "Processing file on server...",
    generatingLatex: "Generating LaTeX file...",
    success: "Completed successfully!",
    errorProcessing: "Error during processing",
    requestCancelled: "Request cancelled",
    documentSaved: "Document saved",
    
    // Mots clés pour les emojis de statut
    waking: "Waking",
    sending: "Sending",
    processing: "Processing",
    generating: "Generating",
    completed: "Completed",
    error: "Error",
    
    // Conseils pendant le chargement (tips)
    tip1: "LaTeX was created in 1984 by Leslie Lamport.",
    tip2: "LaTeX is used by more than 80% of mathematicians.",
    tip3: "The name 'LaTeX' comes from 'Lamport TeX'.",
    tip4: "LaTeX is particularly appreciated for its handling of mathematical formulas.",
    tip5: "LaTeX is free and open source software.",
    tip6: "LaTeX is used by the world's leading universities.",
    tip7: "LaTeX can automatically generate bibliographies with BibTeX.",
    tip8: "Most scientific publications are written in LaTeX.",
    tip9: "There are more than 5000 packages for LaTeX, each offering additional features.",
    tip10: "LaTeX can generate documents in any language.",
    tip11: "LaTeX allows you to create presentations, posters, CVs, and even entire books.",
    tip12: "TeX, the system on which LaTeX is based, was created by Donald Knuth in 1978.",
    tip13: "LaTeX is pronounced 'Lah-tek' and not 'Lay-teks'.",
    
    // Annulation de requête
    cancelRequest: "Cancel request",
    requestCancelledByUser: "Request cancelled by user",
    
    // Messages d'erreur
    errorNoFile: "Please select a PDF file",
    errorServerNotReady: "Unable to wake up the server. Please try again in a few moments.",
    errorNoFileToDownload: "No file to download",
    errorNoLogsToDownload: "No error log file to download",
    requestCancelledRefresh: "Request cancelled. Refresh the page to try again.",
    // Onglet Général
    pdfFile: "PDF File",
    pageDetected: "page detected",
    pagesDetected: "pages detected",
    
    // Onglets
    tabGeneral: "General",
    tabGeneralDesc: "File and title",
    tabLanguage: "Languages",
    tabLanguageDesc: "Source and target",
    tabLayout: "Layout",
    tabLayoutDesc: "Format and margins",
    tabContent: "Content",
    tabContentDesc: "Special sections",
    tabAI: "AI",
    tabAIDesc: "Model and quality",
    
    // Langues
    sourceLanguage: "Source Language",
    targetLanguage: "Target Language",
    searchLanguage: "Search language...",
    translationNote: "Translation will preserve layout and mathematical formulas.",
    
    // Mise en page
    pageFormat: "Page format",
    fontSize: "Font Size (pt)",
    paragraphSpacing: "Paragraph Spacing",
    spacingSingle: "Single (1.0)",
    spacingComfortable: "Comfortable (1.15)",
    spacingWide: "Wide (1.5)",
    spacingDouble: "Double (2.0)",
    margins: "Margins (cm)",
    marginTop: "Top",
    marginRight: "Right",
    marginBottom: "Bottom",
    marginLeft: "Left",
    fontFamily: "Document Font",
    fontDefault: "Computer Modern (default)",
    fontTimes: "Times New Roman",
    fontHelvetica: "Helvetica",
    fontPalatino: "Palatino",
    fontBookman: "Bookman",
    fontCharter: "Charter",
    fontLibertine: "Libertine",
    resetMargins: "Reset margins",
    documentMargins: "Document Margins",
    betaCode: "Beta code",
    betaCodeInput: "Enter your beta code",
    betaCodeButton: "Validate beta code",
    betaCodeSuccess: "Beta code accepted",
    betaCodeError: "Invalid beta code",
    betaBadge: "Private beta",
    betaDescription: "This version is under development and is not yet available to the public. Please wait and contact us if you have any questions or suggestions.",
    giveFeedback: "Give your feedback in 1 minute !",
    betaTitle: "Beta version",
    getStarted: "Get started now !",
    
    // Contenu
    includeIntuition: "Include intuitions",
    includeRetenir: "Include key points",
    includeVulgarisation: "Include simplified explanations",
    includeRecap: "Include summary sheets",
    includeGraph: "Include graphs",
    includeShapes: "Include geometric shapes",
    shapesDescription: "Include geometric shapes in the document using LaTeX/TikZ",
    graphDescription: "Include graphs in the document",
    configure: "Configure",
    vulgarizationNone: "No simplification",
    vulgarizationMinimal: "Level 1 - Minimal",
    vulgarizationLight: "Level 2 - Light",
    vulgarizationMedium: "Level 3 - Medium",
    vulgarizationHigh: "Level 4 - Everyday analogies",
    vulgarizationMaximal: "Level 5 - Creative metaphors",
    includeIllustrations: "Include illustrations descriptions",
    includeDefinitions: "Include definitions",
    extractRealImages: "Extract and include real images",
    includeFinalRecapPage: "Include final recap page",
    highlightMode: "AI Highlighter Mode: highlight important elements to remember",
    detectGraphs: "Detect graphs",
    pedagogicalElements: "Pedagogical elements",
    intuitionDescription: "Intuition: provide an intuitive explanation of the concept discussed in this section. It helps to understand the idea in a more concrete way.",
    retenirDescription: "Key Points: summarize the key points to remember from this section. It includes the key formulas and definitions.",
    vulgarisationDescription: "Simplified Explanation: explain the concepts in a simplified way. It uses analogies and accessible vocabulary to facilitate understanding.",
    summariesAndOverviews: "Summaries and Overviews",
    recapDescription: "Summary: summarize the main concept of this section.",
    finalRecapDescription: "Final Summary: summarize the key points of the entire document.",
    visualElements: "Visual elements",
    illustrationsDescription: "Illustrations: include descriptions of the illustrations in the document.",
    extractImagesDescription: "Extract and include images",
    otherFeatures: "Other features",
    definitionsDescription: "Definitions: include the key definitions of this section.",
    definitionsTitle: "Definitions",
    definitionsPreviewText: "This box contains the key definitions of this section. It provides a precise and formal explanation of the concepts discussed.",
    highlightDescription: "Highlight important elements to remember",
    vulgarizationLevel: "Vulgarization level",
    // IA
    processingQuality: "Processing Quality:",
    fast: "Fast - Basic quality",
    standard: "Standard - Balanced",
    highQuality: "High quality - Better content",
    premium: "Premium - Maximum quality",
    estimatedTime: "Estimated time for a document of",
    estimatedTimeLabel: "Estimated time:",
    pages: "pages",
    loadDocToSeeTime: "Load a document to see precise estimated times",
    modelFastTitle: "Fast",
    modelFastDesc: "AI engine with rapid analysis - For tests or simple documents",
    modelStandardTitle: "Standard",
    modelStandardDesc: "AI engine with standard analysis - For everyday use",
    modelHighQualityTitle: "High quality",
    modelHighQualityDesc: "AI engine with in-depth analysis - For complex technical content",
    modelPremiumTitle: "Premium",
    modelPremiumDesc: "Ultra advanced AI engine - Superior quality and faster processing for all document types",
    analyzingSlides: "Analyzing slides...",
    extractingContent: "Extracting content...",
    generatingLatex: "Generating LaTeX code...",
    formattingDocument: "Formatting document...",
    finalizingOutput: "Finalizing output...",
    preparingDownload: "Preparing download...",
    
    // Instructions spécifiques de l'IA
    aiInstructionsTitle: "Specific Instructions",
    aiInstructionsInfo: "Tell me how you want to customize your LaTeX document:",
    aiInstructionsExample1: "« Focus on practical examples »",
    aiInstructionsExample2: "« Use a more formal style for explaining concepts »",
    aiInstructionsExample3: "« Simplify even more advanced mathematical concepts »",
    aiInstructionsPlaceholder: "Type your specific instructions here...",
    modelHigh_qualityTitle: "High quality",
    // Téléchargement
    downloadFilename: "Download filename:",
    downloadLatex: "Download LaTeX file",
    downloadPDF: "Download PDF",
    downloadLogs: "Download error logs",
    downloadNote: "Note: The LaTeX file is ready to be compiled with Overleaf. The PDF might not be available if server compilation failed.",
    
    // Interface langue
    switchToEnglish: "English",
    switchToFrench: "Français",

    backToHome: "Back to home",
    
    // Erreurs
    errorRefresh: "Try refreshing the page or try again later.",
    
    // Chargement
    loadingHint: "Processing is usually slow... Perfect time to grab a coffee! ☕",
    
    // Modals de configuration
    configIntuition: "Configure \"Intuition\" Boxes",
    configRetenir: "Configure \"Key Points\" Boxes",
    configVulgarisation: "Configure \"Simplified Explanation\" Boxes",
    configRecap: "Configure \"Summary\" Boxes",
    configDefinitions: "Configure \"Definitions\" Boxes",
    preview: "Preview",
    color: "Color:",
    titleFont: "Title Font:",
    contentFont: "Content Font:",
    icon: "Icon:",
    borderStyle: "Border Style:",
    background: "Background:",
    close: "Close",
    save: "Save",
    profile: "Profile",
    // PDF Preview
    pdfPreview: "PDF Preview",
    showPdfPreview: "Show PDF Preview",
    saveToDocuments: "Save to My Documents",
    editDocument: "Edit document",
    modelHigh_qualityDesc: "AI engine with in-depth analysis - For complex technical content",
    
    // Titres des boîtes
    intuitionTitle: "Intuition",
    retenirTitle: "Key Points",
    vulgarisationTitle: "Simplified Explanation",
    definitionsTitle: "Definitions",
    recapTitle: "Summary",
    
    // Textes d'aperçu
    intuitionPreviewText: "This box provides an intuitive explanation of the concept discussed in this section. It helps to understand the idea in a more concrete way.",
    retenirPreviewText: "This box contains the key points to remember from this section. It summarizes the key formulas and definitions.",
    vulgarisationPreviewText: "This box explains the concepts in a simplified way. It uses analogies and accessible vocabulary to facilitate understanding.",
    definitionsPreviewText: "This box contains the key definitions of this section. It provides a precise and formal explanation of the concepts discussed.",
    // Textes de récapitulatif
    recapObjective: "Objective:",
    recapObjectiveText: "Summarize the main concept of this section.",
    recapPrinciple: "Central Principle:",
    recapPrincipleText: "Concise explanation of the fundamental idea.",
    recapPoints: "Key Points:",
    recapPoint1: "First important point",
    recapPoint2: "Second important point",
    recapPoint3: "Third important point",
    
    // Couleurs
    colorGreen: "Green",
    colorBlue: "Blue",
    colorRed: "Red",
    colorYellow: "Yellow",
    colorPurple: "Purple",
    colorGray: "Gray",
    colorOrange: "Orange",
    colorTeal: "Teal",
    
    // Icônes
    iconBulb: "Bulb",
    iconThought: "Thought Bubble",
    iconBrain: "Brain",
    iconCompass: "Compass",
    iconMagic: "Magic Wand",
    iconBookmark: "Bookmark",
    iconCheck: "Checkmark",
    iconStar: "Star",
    iconExclamation: "Exclamation Mark",
    iconMemory: "Memory",
    iconComment: "Comment",
    iconInfo: "Info",
    iconQuestion: "Question Mark",
    iconGlasses: "Glasses",
    iconHand: "Hand Pointing",
    iconList: "List",
    iconAltList: "Alternative List",
    iconTasks: "Tasks",
    iconDocument: "Document",
    iconChart: "Chart",
    
    // Styles de bordure
    borderSimple: "Simple (1pt)",
    borderDouble: "Double",
    borderDotted: "Dotted",
    borderDashed: "Dashed",
    borderThick: "Thick (3pt)",
    
    // Arrière-plans
    bgSolid: "Solid",
    bgGrid: "Grid",
    bgDots: "Dots",
    bgCrosshatch: "Crosshatch",
    bgGradient: "Gradient",

    // Chat Interface
    openChat: "Open AI Assistant",
    closeChat: "Close Assistant",
    deleteMessage: "Delete this message",
    sendMessage: "Send",
    chatPlaceholder: "Type your instructions here...",
    chatTitle: "AI Assistant",
    chatDescription: "I help you customize your document",

    // Profile Page
    myProfile: "My Profile",
    backToApp: "Back to app",
    loadingProfile: "Loading your profile...",
    profileOverview: "Profile Overview",
    dashboard: "Dashboard",
    myDocuments: "My Documents",
    preferences: "Preferences",
    accountSettings: "Account Settings",
    affiliateProgram: "Affiliate Program",
    comingSoon: "Coming Soon",
    underDevelopment: "Under Development",
    underDevelopmentMessage: "This feature is currently under development. It will be available soon!",
    stayTuned: "Stay tuned for updates.",
    viewProfile: "View profile",
    myProfile: "My Profile",
    uploadPhoto: "Upload photo",
    registrationDate: "Registration date",
    accountStatus: "Account status",
    statusActive: "Active",
    statusInactive: "Inactive",
    statusPending: "Pending",
    betaTester: "Beta Tester",
    logout: "Logout",
    documents: "Documents",
    searchDocuments: "Search documents...",
    allDocuments: "All documents",
    slidesOnly: "Slides only",
    textDocumentsOnly: "Text documents only",
    noDocumentsFound: "No documents found for this search",
    loadingDocuments: "Loading your documents...",
    upgradeForMoreFeatures: "Upgrade for more features",
    upgradeToPremium: "Upgrade to Premium",

    // Other
    connected: "Connected",
    viewProfile: "View profile",
    myProfile: "My Profile",
    logout: "Logout",
    
    // Registration form
    completeYourProfile: "Complete Your Profile",
    registrationDescription: "Please complete the following information to personalize your experience. This will help us better understand your needs and improve our service.",
    displayName: "Display Name",
    displayNamePlaceholder: "How would you like to be called?",
    occupation: "Occupation",
    selectOccupation: "Select your occupation",
    occupationStudent: "Student",
    occupationTeacher: "Teacher",
    occupationResearcher: "Researcher",
    occupationProfessional: "Professional",
    occupationOther: "Other",
    organization: "Organization",
    organizationPlaceholder: "Name of your university, school or company",
    fieldOfStudy: "Field of study",
    fieldOfStudyPlaceholder: "E.g., Mathematics, Computer Science, Physics",
    country: "Country",
    selectCountry: "Select your country",
    countryFrance: "France",
    countryUSA: "United States",
    countryCanada: "Canada",
    countrySwitzerland: "Switzerland",
    countryBelgium: "Belgium",
    countryOther: "Other country",
    bio: "Bio (optional)",
    bioPlaceholder: "Tell us a bit about yourself and what you hope to accomplish with MyTekX",
    skip: "Skip for now",
    saveProfile: "Save Profile",
    saving: "Saving...",
    privacyNote: "By saving your profile, you agree to our privacy policy. Your information will never be shared without your consent.",
    errorRequiredField: "This field is required",
    errorNameTooShort: "Name must be at least 3 characters long",
    errorSavingData: "An error occurred while saving. Please try again.",
    settings: "Settings",
    noDocumentsYet: "You don't have any documents yet",
    viewDocumentsDesc: "Click to view and manage your documents",
    backToProfile: "Back to profile",


    // Documents
    searchDocuments: "Search documents...",
    allDocuments: "All documents",
    slidesOnly: "Slides only",
    textDocumentsOnly: "Text documents only",
    noDocumentsFound: "No documents found for this search",
    loadingDocuments: "Loading your documents...",
    viewDocument: "View document",
    downloadDocument: "Download document",
    viewPDF: "View PDF",
    downloadTex: "Opens a window with LaTeX code - Copy and paste this text into a LaTeX editor (like Overleaf) to edit it",
    deleteDocument: "Delete document",
    delete: "Delete",
    confirmDeleteTitle: "Delete confirmation",
    confirmDelete: "Are you sure you want to delete this document? This action is irreversible.",
    confirmDeleteButton: "Yes, delete",
    cancel: "Cancel",
    documentDeleted: "Document successfully deleted",
    deleteError: "Error deleting document",
    page: "page",
    pages: "pages",
    slides: "Slides",
    textDocument: "Text document",
    downloadSection: "Download Section",
    filenameLabel: "Filename",
    downloadLatexFile: "Download LaTeX File",
    lastUpdated: "Last updated",
    // FAQ section
    faqTitle: "Frequently Asked Questions",
    faqSubtitle: "Got questions? We've got you covered.",

    //Confidentiality section
    whoWeAre: "Who we are",
    privacyPolicyIntro: "Welcome to MyTekX, a powerful tool that allows you to easily convert your PowerPoint presentations and documents into high-quality LaTeX. This privacy policy explains how we collect, use, and protect your data when you use our service.",
    dataCollected: "Data collected",
    dataCollectedIntro: "When you use MyTekX, we collect certain information to provide and improve our service. This information is used to personalize your experience and to analyze how you use the service.",
    dataItem1: "Your email address",
    dataItem2: "Your usage data",
    dataItem3: "Your documents",
    dataItem4: "Your profile information",
    dataItem5: "Your interactions with the service",
    dataItem6: "Your device information",
    dataItem7: "Your IP address",
    
    howWeUseData: "How we use your data",
    dataUsageDescription: "We use your data to personalize your experience, analyze your usage, and improve our service. We do not share your data with third parties without your consent.",
    dataSharing: "Data sharing",
    dataSharingPolicy: "We do not share your data with third parties without your consent.",

    dataSecurity: "Data security",
    dataSecurityDescription: "We implement security measures to protect your data. However, no method of transmission over the internet is 100% secure.",
    userRights: "User rights",
    userRightsDescription: "You have the right to access, correct, or delete your data. You can also request that we stop using your data for certain purposes.",
    contactForRights: "Contact us for more information about your rights.",
    cookies: "Cookies",
    cookiesDescription: "We use cookies to personalize your experience. You can disable cookies in your browser settings.",
    policyChanges: "Policy changes",
    policyChangesDescription: "We reserve the right to update this privacy policy at any time. We will notify you of significant changes via email or through the service.",
    // Footer section
    footerNavigation: "Navigation",
    footerHome: "Home",
    footerResources: "Resources",
    footerBlog: "Blog",
    footerTutorials: "Tutorials",
    footerSupport: "Support",
    footerDocumentation: "Documentation",
    footerContact: "Contact",
    footerContactUs: "Contact Us",
    footerRights: "All rights reserved",
    comingSoon: "Coming Soon",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    legalNotice: "Legal Notice",

    // Final CTA section
    finalCtaTitle: "Ready to transform the way you study?",
    finalCtaSubtitle: "START TODAY",
    finalCtaDescription: "Join the students and teachers already using MyTekX to enhance their learning experience.",
    finalCtaTryButton: "Try for free",
    finalCtaLearnButton: "Learn more",
    personalInfo: "Personal Information",
    privacySecurity: "Privacy & Security",
    latinAlphabetOnly: "Latin alphabets only",
    latinAlphabetMessage: "Currently, only target languages using the Latin alphabet are available. Languages with other alphabets (Arabic, Chinese, Hebrew, Cyrillic, etc.) are under development.",
    otherAlphabetsComingSoon: "Other alphabets coming soon",
  }
};

// Création du contextez
const LanguageContext = createContext();

// Hook personnalisé pour utiliser le contexte
export const useLanguage = () => useContext(LanguageContext);

// Fournisseur du contexte
export const LanguageProvider = ({ children }) => {
  // Initialiser avec la langue sauvegardée ou 'en' par défaut
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('mytekx-language');
    return savedLanguage || 'en';
  });
  
  // Sauvegarder la langue dans localStorage à chaque changement
  const handleSetLanguage = (newLanguage) => {
    setLanguage(newLanguage);
    localStorage.setItem('mytekx-language', newLanguage);
  };
  
  const toggleLanguage = () => {
    const newLanguage = language === 'fr' ? 'en' : 'fr';
    handleSetLanguage(newLanguage);
  };
  
  // Raccourci pour accéder aux traductions
  const t = (key) => {
    return translations[language][key] || key;
  };
  
  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext; 